language: node_js
node_js:
  - node

before_script:
  - npm install -g webpack

script:
  - npm install
  - cd src/containers
  - ls
  - webpack --config webpack.prod.js
  - cp index.prod.html dist/index.html

install:
  - npm install firebase-tools -g

after_success:
  - firebase deploy --only hosting --token ${FIREBASE_TOKEN}
