language: node_js
node_js:
  - node

before_script:
  - npm install -g webpack

script:
  - npm install
  - webpack --config webpack.prod.js
  - cp index.prod.html dist/index.html

install:
  - npm install firebase-tools -g

after_success:
  - cd dist
  - firebase login --email ${FIREBASE_LOGIN} --pasword${FIREBASE_PASSWORD}
  - firebase init
  - firebase deploy
