export const PROJECTS = 'PROJECTS'
export const CONTEXTS = 'CONTEXTS'
export const PROJECT = 'PROJECT'
export const CONTEXT = 'CONTEXT'
export const INBOX = 'INBOX'
export const TODAY = 'TODAY'
export const NEXT = 'NEXT'
export const SOMEDAY = 'SOMEDAY'
